### ISSUE TITLE
Weird intro sentence

### ISSUE THREAD

**Issue by wooorm** [cmda-vr/documentation#2]
https://github.com/cmda-vr/documentation/blame/1bd968bef5b7ce675ebcb1047946dabde0807205/introduction/INTRODUCTION.md#L9

`Dit alles in de vorm van een website die dient als toolkit.` should probably be more like `Als oplossing ontwikkel ik een website die dient als toolkit` or something similar?

**Comment by dandevri** [comment]
Agreed, sounds more professional.
